server:
  port: 8080
keycloak:
  realm: Demo-Realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: gateway-microservice
  credentials:
    secret: XXXXXXXXXXXXXXXXXXXXXXXXX
  use-resource-role-mappings: true
  bearer-only: true